"""
CSV & JSON Handling -- Practice Examples
========================================
Day 8: File Handling & Data Processing

This script demonstrates:
1. Reading CSV files (csv.reader, csv.DictReader)
2. Writing CSV files (csv.writer, csv.DictWriter)
3. Reading JSON files (json.load)
4. Writing JSON files (json.dump, json.dumps)
5. Converting between CSV and JSON formats
6. Pretty printing JSON

All examples use the sample_data.csv and sample_data.json files
located in the same directory.
"""

import csv
import json
import os
from pathlib import Path

# Get the directory where this script is located
SCRIPT_DIR = Path(__file__).parent

# File paths for sample data
CSV_FILE = SCRIPT_DIR / "sample_data.csv"
JSON_FILE = SCRIPT_DIR / "sample_data.json"

# Output file paths (generated by this script)
CSV_OUTPUT = SCRIPT_DIR / "output_employees.csv"
JSON_OUTPUT = SCRIPT_DIR / "output_employees.json"
CONVERTED_CSV = SCRIPT_DIR / "converted_from_json.csv"
CONVERTED_JSON = SCRIPT_DIR / "converted_from_csv.json"


# ============================================================
# 1. READING CSV FILES
# ============================================================

def example_csv_reader():
    """
    Demonstrate reading a CSV file using csv.reader.
    Each row is returned as a list of strings.
    """
    print("=" * 60)
    print("  Example 1: Reading CSV with csv.reader")
    print("=" * 60)

    with open(CSV_FILE, "r", newline="", encoding="utf-8") as f:
        reader = csv.reader(f)

        # Read the header row
        header = next(reader)
        print(f"  Columns: {header}")
        print()

        # Read and display each data row
        for row_num, row in enumerate(reader, start=1):
            print(f"  Row {row_num}: {row}")

    print()


def example_csv_dictreader():
    """
    Demonstrate reading a CSV file using csv.DictReader.
    Each row is returned as a dictionary with column names as keys.
    """
    print("=" * 60)
    print("  Example 2: Reading CSV with csv.DictReader")
    print("=" * 60)

    with open(CSV_FILE, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        print(f"  Fieldnames: {reader.fieldnames}")
        print()

        # Access each field by name -- much more readable!
        for row in reader:
            name = row["name"]
            dept = row["department"]
            salary = row["salary"]
            print(f"  {name:<20} | Dept: {dept:<15} | Salary: ${salary}")

    print()


# ============================================================
# 2. WRITING CSV FILES
# ============================================================

def example_csv_writer():
    """
    Demonstrate writing a CSV file using csv.writer.
    """
    print("=" * 60)
    print("  Example 3: Writing CSV with csv.writer")
    print("=" * 60)

    # Sample data to write
    header = ["product", "category", "price", "quantity"]
    products = [
        ["Laptop", "Electronics", 999.99, 50],
        ["Desk Chair", "Furniture", 249.99, 120],
        ["Python Book", "Books", 39.99, 300],
        ["Monitor", "Electronics", 449.99, 75],
        ["Notebook", "Stationery", 4.99, 1000],
    ]

    with open(CSV_OUTPUT, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(header)      # Write header
        writer.writerows(products)   # Write all data rows at once

    print(f"   Written {len(products)} rows to: {CSV_OUTPUT.name}")

    # Verify by reading back
    with open(CSV_OUTPUT, "r", newline="", encoding="utf-8") as f:
        content = f.read()
    print(f"\n  File contents:\n{content}")


def example_csv_dictwriter():
    """
    Demonstrate writing a CSV file using csv.DictWriter.
    """
    print("=" * 60)
    print("  Example 4: Writing CSV with csv.DictWriter")
    print("=" * 60)

    fieldnames = ["city", "country", "population", "timezone"]
    cities = [
        {"city": "Tokyo", "country": "Japan", "population": 13960000, "timezone": "JST"},
        {"city": "Mumbai", "country": "India", "population": 12440000, "timezone": "IST"},
        {"city": "São Paulo", "country": "Brazil", "population": 12330000, "timezone": "BRT"},
        {"city": "Berlin", "country": "Germany", "population": 3645000, "timezone": "CET"},
    ]

    output_path = SCRIPT_DIR / "cities.csv"
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(cities)

    print(f"   Written {len(cities)} cities to: {output_path.name}")

    # Read back and display
    with open(output_path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pop = int(row["population"])
            print(f"  {row['city']:<12} | {row['country']:<10} | "
                  f"Pop: {pop:>12,} | TZ: {row['timezone']}")
    print()


# ============================================================
# 3. READING JSON FILES
# ============================================================

def example_json_load():
    """
    Demonstrate reading a JSON file using json.load.
    """
    print("=" * 60)
    print("  Example 5: Reading JSON with json.load")
    print("=" * 60)

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Display structure info
    if isinstance(data, dict) and "employees" in data:
        employees = data["employees"]
        print(f"  Loaded {len(employees)} employees from JSON\n")

        for emp in employees:
            print(f"  ID: {emp['id']} | {emp['name']:<20} | "
                  f"Dept: {emp['department']:<15} | Salary: ${emp['salary']:,}")
    elif isinstance(data, list):
        print(f"  Loaded {len(data)} records from JSON\n")
        for item in data[:5]:  # Show first 5
            print(f"  {item}")

    print()


def example_json_loads():
    """
    Demonstrate parsing a JSON string using json.loads.
    """
    print("=" * 60)
    print("  Example 6: Parsing JSON string with json.loads")
    print("=" * 60)

    # Simulating JSON data received from an API
    api_response = '''
    {
        "status": "success",
        "data": {
            "user": "alice",
            "role": "admin",
            "permissions": ["read", "write", "delete"],
            "active": true
        },
        "timestamp": "2025-05-15T10:30:00Z"
    }
    '''

    # Parse the JSON string
    result = json.loads(api_response)

    print(f"  Status: {result['status']}")
    print(f"  User:   {result['data']['user']}")
    print(f"  Role:   {result['data']['role']}")
    print(f"  Perms:  {', '.join(result['data']['permissions'])}")
    print(f"  Active: {result['data']['active']}")
    print(f"  Time:   {result['timestamp']}")
    print()


# ============================================================
# 4. WRITING JSON FILES
# ============================================================

def example_json_dump():
    """
    Demonstrate writing Python data to a JSON file using json.dump.
    """
    print("=" * 60)
    print("  Example 7: Writing JSON with json.dump")
    print("=" * 60)

    # Python data structure
    config = {
        "app_name": "DataProcessor",
        "version": "2.1.0",
        "debug": False,
        "database": {
            "host": "localhost",
            "port": 5432,
            "name": "analytics_db",
            "credentials": {
                "user": "app_user",
                "password_env": "DB_PASSWORD"
            }
        },
        "features": {
            "caching": True,
            "rate_limiting": True,
            "max_connections": 100
        },
        "allowed_origins": [
            "https://example.com",
            "https://api.example.com"
        ]
    }

    output_path = SCRIPT_DIR / "config_output.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=4, sort_keys=True)

    print(f"   Config written to: {output_path.name}")

    # Read back and display
    with open(output_path, "r", encoding="utf-8") as f:
        content = f.read()
    print(f"\n{content}")


def example_json_dumps():
    """
    Demonstrate converting Python objects to JSON strings using json.dumps.
    Shows pretty printing capabilities.
    """
    print("=" * 60)
    print("  Example 8: Pretty Printing JSON with json.dumps")
    print("=" * 60)

    data = {
        "students": [
            {"name": "Alice", "grade": "A", "gpa": 3.9},
            {"name": "Bob", "grade": "B+", "gpa": 3.4},
            {"name": "Charlie", "grade": "A-", "gpa": 3.7},
        ],
        "class": "Computer Science 101",
        "semester": "Fall 2025"
    }

    # Compact format (single line)
    compact = json.dumps(data, separators=(",", ":"))
    print(f"  Compact ({len(compact)} chars):")
    print(f"  {compact[:80]}...")

    # Pretty format
    pretty = json.dumps(data, indent=2, sort_keys=True)
    print(f"\n  Pretty ({len(pretty)} chars):")
    print(pretty)
    print()


# ============================================================
# 5. FORMAT CONVERSION
# ============================================================

def example_csv_to_json():
    """
    Convert CSV data to JSON format.
    """
    print("=" * 60)
    print("  Example 9: Converting CSV  JSON")
    print("=" * 60)

    # Read CSV data
    employees = []
    with open(CSV_FILE, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Convert numeric fields from strings
            row["id"] = int(row["id"])
            row["salary"] = int(row["salary"])
            employees.append(row)

    # Write as JSON
    output = {"employees": employees, "count": len(employees)}
    with open(CONVERTED_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=4)

    print(f"   Converted {len(employees)} records from CSV to JSON")
    print(f"  Output: {CONVERTED_JSON.name}")

    # Show preview
    with open(CONVERTED_JSON, "r", encoding="utf-8") as f:
        content = f.read()
    # Show first 500 characters
    preview = content[:500] + ("..." if len(content) > 500 else "")
    print(f"\n  Preview:\n{preview}")
    print()


def example_json_to_csv():
    """
    Convert JSON data to CSV format.
    """
    print("=" * 60)
    print("  Example 10: Converting JSON  CSV")
    print("=" * 60)

    # Read JSON data
    with open(JSON_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Extract employees list
    employees = data.get("employees", data) if isinstance(data, dict) else data

    if not employees:
        print("    No employee data found in JSON file.")
        return

    # Write as CSV
    fieldnames = list(employees[0].keys())

    with open(CONVERTED_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(employees)

    print(f"   Converted {len(employees)} records from JSON to CSV")
    print(f"  Output: {CONVERTED_CSV.name}")

    # Show the CSV content
    with open(CONVERTED_CSV, "r", encoding="utf-8") as f:
        content = f.read()
    print(f"\n  CSV content:\n{content}")


# ============================================================
# MAIN EXECUTION
# ============================================================

def main():
    """Run all CSV and JSON handling examples."""
    print("\n" + "" * 60)
    print("  CSV & JSON Handling -- Practice Examples")
    print("" * 60 + "\n")

    # Verify sample data files exist
    if not CSV_FILE.exists():
        print(f"    Sample CSV file not found: {CSV_FILE}")
        print("  Please ensure sample_data.csv exists in the practice directory.")
        return

    if not JSON_FILE.exists():
        print(f"    Sample JSON file not found: {JSON_FILE}")
        print("  Please ensure sample_data.json exists in the practice directory.")
        return

    # Run all examples
    example_csv_reader()
    example_csv_dictreader()
    example_csv_writer()
    example_csv_dictwriter()
    example_json_load()
    example_json_loads()
    example_json_dump()
    example_json_dumps()
    example_csv_to_json()
    example_json_to_csv()

    # Clean up generated files (optional -- comment out to keep them)
    # cleanup_files = [CSV_OUTPUT, JSON_OUTPUT, CONVERTED_CSV, CONVERTED_JSON]
    # for f in cleanup_files:
    #     if f.exists():
    #         f.unlink()
    #         print(f"   Cleaned up: {f.name}")

    print("\n" * 60)
    print("  All CSV & JSON examples completed successfully! ")
    print("" * 60 + "\n")


if __name__ == "__main__":
    main()
